/**
 * BriefScreen.tsx — architect brief (T15 screen half).
 * Renders the POST /brief response: ₹ budget table with "est." tags and vendor
 * links, total row, legal checklist, and a "Send to architect" mailto button.
 *
 * Usage: <BriefScreen brief={brief} visible={show} onClose={() => setShow(false)} />
 */

import React from "react";
import type { BriefData } from "./types";
import "./rail.css";

export interface BriefScreenProps {
  brief: BriefData | null;
  visible: boolean;
  onClose: () => void;
}

const inr = (n: number) => "₹" + n.toLocaleString("en-IN");

function buildMailto(brief: BriefData): string {
  const lines: string[] = [];
  lines.push("Renovation brief (generated by Vistara)");
  lines.push("");
  lines.push("BUDGET (all figures are estimates):");
  for (const b of brief.budget) {
    lines.push(`- ${b.item}: ${inr(b.estimate_inr)} (est.)${b.source_url ? ` — ${b.source_url}` : ""}`);
  }
  lines.push(`TOTAL ESTIMATE: ${inr(brief.total_estimate_inr)}`);
  lines.push("");
  lines.push("APPROVALS / LEGAL CHECKLIST:");
  for (const l of brief.legal) {
    lines.push(
      `- [${l.required ? "REQUIRED" : "not required"}] ${l.step} — ${l.detail}`
    );
  }
  lines.push("");
  lines.push("Prices are grounded estimates with cited links, not quotes.");
  const subject = encodeURIComponent("Renovation brief from Vistara");
  const body = encodeURIComponent(lines.join("\n"));
  return `mailto:?subject=${subject}&body=${body}`;
}

export default function BriefScreen({ brief, visible, onClose }: BriefScreenProps) {
  if (!visible) return null;

  return (
    <div className="ghar-brief" role="dialog" aria-label="Architect brief">
      <div className="ghar-brief-header">
        <h2>Architect brief</h2>
        <button className="ghar-brief-close" onClick={onClose} aria-label="Close">
          &times;
        </button>
      </div>

      {brief === null ? (
        <div className="ghar-brief-loading">Compiling brief…</div>
      ) : (
        <div className="ghar-brief-body">
          <h3>Budget <span className="ghar-est-tag">all estimates</span></h3>
          <table className="ghar-brief-table">
            <tbody>
              {brief.budget.map((b, i) => (
                <tr key={i}>
                  <td className="ghar-brief-item">
                    {b.item}
                    {b.source_url && (
                      <a
                        href={b.source_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="ghar-vendor-link"
                      >
                        vendor
                      </a>
                    )}
                  </td>
                  <td className="ghar-brief-amount">
                    {inr(b.estimate_inr)} <span className="ghar-est-tag">est.</span>
                  </td>
                </tr>
              ))}
              <tr className="ghar-brief-total">
                <td>Total</td>
                <td className="ghar-brief-amount">
                  {inr(brief.total_estimate_inr)}{" "}
                  <span className="ghar-est-tag">est.</span>
                </td>
              </tr>
            </tbody>
          </table>

          <h3>Approvals &amp; legal</h3>
          <ul className="ghar-legal-list">
            {brief.legal.map((l, i) => (
              <li key={i} className={l.required ? "is-required" : "is-optional"}>
                <span className="ghar-legal-mark">{l.required ? "✓" : "–"}</span>
                <span>
                  <strong>{l.step}</strong>
                  <em>{l.detail}</em>
                </span>
              </li>
            ))}
          </ul>

          <a className="ghar-brief-send" href={buildMailto(brief)}>
            Send to architect
          </a>
        </div>
      )}
    </div>
  );
}
