/**
 * BuildPack.tsx — the final deliverable screen: floor plan + report.
 * Replaces BriefScreen usage in App (BriefScreen itself is untouched).
 *
 * Sections:
 *   - Floor plan image (or "drawing your plan…" skeleton) + ILLUSTRATIVE disclaimer
 *   - Per-room specs table (brief.rooms, when the server returns it)
 *   - Budget table (existing shape; source_url may be null)
 *   - Materials & equipment table (brief.materials_and_equipment, when present)
 *   - Legal checklist + total
 *   - "Send to architect" mailto with a text summary of everything
 */

import React, { useState } from "react";
import "./buildpack.css";

export interface BuildPackProps {
  brief: any | null;
  planUrl: string | null;
  visible: boolean;
  onClose: () => void;
}

// Same derivation as tools.ts — BuildPack doesn't receive serverUrl as a prop.
const SERVER_URL =
  process.env.REACT_APP_SERVER_URL || "http://localhost:8000";

const inr = (n: number | null | undefined) =>
  typeof n === "number" ? "₹" + n.toLocaleString("en-IN") : "—";

/** Strip the server origin off planUrl so the server gets its own /static path. */
function toStaticPath(planUrl: string | null): string | null {
  if (!planUrl) return null;
  if (planUrl.startsWith("/static/")) return planUrl;
  const origin = SERVER_URL.replace(/\/$/, "");
  if (planUrl.startsWith(origin)) {
    const path = planUrl.slice(origin.length);
    return path.startsWith("/static/") ? path : null;
  }
  return null;
}

function buildMailto(brief: any, planUrl: string | null): string {
  const lines: string[] = [];
  lines.push("Home build pack (generated by Vistara)");
  lines.push("");

  if (planUrl) {
    lines.push(`FLOOR PLAN (illustrative concept, not to scale): ${planUrl}`);
    lines.push("");
  }

  const rooms: any[] = Array.isArray(brief?.rooms) ? brief.rooms : [];
  if (rooms.length > 0) {
    lines.push("ROOM SPECS:");
    for (const r of rooms) {
      lines.push(`- ${r.room}: ${r.spec}`);
    }
    lines.push("");
  }

  const budget: any[] = Array.isArray(brief?.budget) ? brief.budget : [];
  if (budget.length > 0) {
    lines.push("BUDGET (all figures are estimates):");
    for (const b of budget) {
      lines.push(
        `- ${b.item}: ${inr(b.estimate_inr)} (est.)${b.source_url ? ` — ${b.source_url}` : ""}`
      );
    }
    lines.push(`TOTAL ESTIMATE: ${inr(brief?.total_estimate_inr)}`);
    lines.push("");
  }

  const materials: any[] = Array.isArray(brief?.materials_and_equipment)
    ? brief.materials_and_equipment
    : [];
  if (materials.length > 0) {
    lines.push("MATERIALS & EQUIPMENT:");
    for (const m of materials) {
      lines.push(`- ${m.item} — ${m.purpose} — ${inr(m.estimate_inr)} (est.)`);
    }
    lines.push("");
  }

  const legal: any[] = Array.isArray(brief?.legal) ? brief.legal : [];
  if (legal.length > 0) {
    lines.push("APPROVALS / LEGAL CHECKLIST:");
    for (const l of legal) {
      lines.push(
        `- [${l.required ? "REQUIRED" : "not required"}] ${l.step} — ${l.detail}`
      );
    }
    lines.push("");
  }

  lines.push(
    "Prices are grounded estimates, not quotes. The floor plan is an illustrative concept, not a construction drawing."
  );
  const subject = encodeURIComponent("Home build pack from Vistara");
  const body = encodeURIComponent(lines.join("\n"));
  return `mailto:?subject=${subject}&body=${body}`;
}

export default function BuildPack({
  brief,
  planUrl,
  visible,
  onClose,
}: BuildPackProps) {
  const [exporting, setExporting] = useState(false);

  if (!visible) return null;

  const downloadPack = async () => {
    if (exporting || brief === null) return;
    setExporting(true);
    try {
      const res = await fetch(`${SERVER_URL}/export`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          brief,
          plan_image_url: toStaticPath(planUrl),
          home_description: null,
        }),
      });
      if (!res.ok) throw new Error(`export failed: ${res.status}`);
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "vistara-architect-pack.html";
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("[buildpack] export failed:", err);
    } finally {
      setExporting(false);
    }
  };

  const rooms: any[] = Array.isArray(brief?.rooms) ? brief.rooms : [];
  const budget: any[] = Array.isArray(brief?.budget) ? brief.budget : [];
  const materials: any[] = Array.isArray(brief?.materials_and_equipment)
    ? brief.materials_and_equipment
    : [];
  const legal: any[] = Array.isArray(brief?.legal) ? brief.legal : [];

  return (
    <div className="ghar-buildpack" role="dialog" aria-label="Home build pack">
      <div className="ghar-buildpack-header">
        <h2>Your build pack</h2>
        <button
          className="ghar-buildpack-close"
          onClick={onClose}
          aria-label="Close"
        >
          &times;
        </button>
      </div>

      <div className="ghar-buildpack-body">
        {/* Floor plan */}
        <section className="ghar-buildpack-section">
          <h3>Floor plan</h3>
          {planUrl ? (
            <img
              className="ghar-buildpack-plan"
              src={planUrl}
              alt="Concept floor plan of your home"
            />
          ) : (
            <div className="ghar-buildpack-plan-skeleton">
              drawing your plan…
            </div>
          )}
          <p className="ghar-buildpack-disclaimer">
            ILLUSTRATIVE concept only — not to scale, not a construction
            drawing. Your architect will produce the real one.
          </p>
        </section>

        {brief === null ? (
          <div className="ghar-buildpack-loading">Compiling your report…</div>
        ) : (
          <>
            {/* Per-room specs */}
            {rooms.length > 0 && (
              <section className="ghar-buildpack-section">
                <h3>Room specs</h3>
                <table className="ghar-buildpack-table">
                  <tbody>
                    {rooms.map((r: any, i: number) => (
                      <tr key={i}>
                        <td className="ghar-buildpack-key">{r.room}</td>
                        <td>{r.spec}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </section>
            )}

            {/* Budget */}
            <section className="ghar-buildpack-section">
              <h3>
                Budget <span className="ghar-buildpack-tag">all estimates</span>
              </h3>
              <table className="ghar-buildpack-table">
                <tbody>
                  {budget.map((b: any, i: number) => (
                    <tr key={i}>
                      <td className="ghar-buildpack-key">
                        {b.item}
                        {b.source_url ? (
                          <a
                            href={b.source_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="ghar-buildpack-link"
                          >
                            vendor
                          </a>
                        ) : null}
                      </td>
                      <td className="ghar-buildpack-amount">
                        {inr(b.estimate_inr)}{" "}
                        <span className="ghar-buildpack-tag">est.</span>
                      </td>
                    </tr>
                  ))}
                  <tr className="ghar-buildpack-total">
                    <td>Total</td>
                    <td className="ghar-buildpack-amount">
                      {inr(brief?.total_estimate_inr)}{" "}
                      <span className="ghar-buildpack-tag">est.</span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </section>

            {/* Materials & equipment */}
            {materials.length > 0 && (
              <section className="ghar-buildpack-section">
                <h3>Materials &amp; equipment</h3>
                <table className="ghar-buildpack-table">
                  <tbody>
                    {materials.map((m: any, i: number) => (
                      <tr key={i}>
                        <td className="ghar-buildpack-key">
                          {m.item}
                          <em className="ghar-buildpack-purpose">
                            {m.purpose}
                          </em>
                        </td>
                        <td className="ghar-buildpack-amount">
                          {inr(m.estimate_inr)}{" "}
                          <span className="ghar-buildpack-tag">est.</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </section>
            )}

            {/* Legal checklist */}
            {legal.length > 0 && (
              <section className="ghar-buildpack-section">
                <h3>Approvals &amp; legal</h3>
                <ul className="ghar-buildpack-legal">
                  {legal.map((l: any, i: number) => (
                    <li
                      key={i}
                      className={l.required ? "is-required" : "is-optional"}
                    >
                      <span className="ghar-buildpack-mark">
                        {l.required ? "✓" : "–"}
                      </span>
                      <span>
                        <strong>{l.step}</strong>
                        <em>{l.detail}</em>
                      </span>
                    </li>
                  ))}
                </ul>
              </section>
            )}

            <div className="ghar-buildpack-actions">
              <a
                className="ghar-buildpack-send"
                href={buildMailto(brief, planUrl)}
              >
                Send to architect
              </a>
              <button
                className="ghar-buildpack-download"
                onClick={downloadPack}
                disabled={exporting}
              >
                {exporting ? "preparing…" : "⬇ Download pack"}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
